### ISSUE TITLE
DFO_MoM missign file error

### ISSUE THREAD

**Issue by webgisdeveloper** [Global-Flood-Assessment/MoMProduction#18]
```python
not found:  /home/cicuser/MoM/Products/GFMS/GFMS_summary/Flood_byStor_2022031700.csv
not found:  /home/cicuser/MoM/Products/GFMS/GFMS_summary/Flood_byStor_2022031706.csv
not found:  /home/cicuser/MoM/Products/GFMS/GFMS_summary/Flood_byStor_2022031712.csv
not found:  /home/cicuser/MoM/Products/GFMS/GFMS_summary/Flood_byStor_2022031718.csv
Traceback (most recent call last):
  File "/home/cicuser/Projects/MoMProduction/DFO_tool.py", line 321, in <module>
    main()
  File "/home/cicuser/Projects/MoMProduction/DFO_tool.py", line 318, in main
    DFO_cron()
  File "/home/cicuser/Projects/MoMProduction/DFO_tool.py", line 312, in DFO_cron
    update_DFO_MoM(datelist[key])
  File "/home/cicuser/Projects/MoMProduction/DFO_MoM.py", line 113, in update_DFO_MoM
    MOM = read_data(MOMOutput)
  File "/home/cicuser/Projects/MoMProduction/utilities.py", line 27, in read_data
    df = pd.read_csv(datafile)
  File "/home/cicuser/miniconda3/envs/mom/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/cicuser/miniconda3/envs/mom/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/cicuser/miniconda3/envs/mom/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/cicuser/miniconda3/envs/mom/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/cicuser/miniconda3/envs/mom/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/cicuser/miniconda3/envs/mom/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/cicuser/miniconda3/envs/mom/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/cicuser/miniconda3/envs/mom/lib/python3.9/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/cicuser/MoM/Products/HWRF/HWRF_MoM/Final_Attributes_2022031718HWRFUpdated.csv'
```

**Comment by straycatcoder** [comment]
fixed date function added
