### ISSUE TITLE
HWRF site may be not reachable: Temporary failure in name resolution

### ISSUE THREAD

**Issue by webgisdeveloper** [Global-Flood-Assessment/MoMProduction#48]
It may be an issue related with JS2.
ConnectionError: HTTPSConnectionPool(host='ftpprd.ncep.noaa.gov', port=443):

```
Traceback (most recent call last):
  File "/home/geogateway/miniconda3/envs/mom/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/geogateway/miniconda3/envs/mom/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/geogateway/miniconda3/envs/mom/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geogateway/miniconda3/envs/mom/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/geogateway/miniconda3/envs/mom/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/geogateway/miniconda3/envs/mom/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/geogateway/miniconda3/envs/mom/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/geogateway/miniconda3/envs/mom/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fcc95bc78e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geogateway/miniconda3/envs/mom/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/geogateway/miniconda3/envs/mom/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/geogateway/miniconda3/envs/mom/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ftpprd.ncep.noaa.gov', port=443): Max retries exceeded with url: /data/nccf/com/hwrf/prod/hwrf.20221123/00 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcc95bc78e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geogateway/MoMProduction/GFMS_tool_debug.py", line 505, in <module>
    main()
  File "/home/geogateway/MoMProduction/GFMS_tool_debug.py", line 502, in main
    GFMS_cron()
  File "/home/geogateway/MoMProduction/GFMS_tool_debug.py", line 445, in GFMS_cron
    hwrf_flag = hwrf_today()
  File "/home/geogateway/MoMProduction/utilities.py", line 81, in hwrf_today
    has_data = url_exits(turl)
  File "/home/geogateway/MoMProduction/utilities.py", line 62, in url_exits
    req = requests.get(aurl)
  File "/home/geogateway/miniconda3/envs/mom/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/geogateway/miniconda3/envs/mom/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/geogateway/miniconda3/envs/mom/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/geogateway/miniconda3/envs/mom/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/geogateway/miniconda3/envs/mom/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ftpprd.ncep.noaa.gov', port=443): Max retries exceeded with url: /data/nccf/com/hwrf/prod/hwrf.20221123/00 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcc95bc78e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```

**Comment by webgisdeveloper** [comment]
it is an issue with Jetstream 2
