### ISSUE TITLE
Incident report: not able to process new DFO data since  20231031

### ISSUE THREAD

**Issue by webgisdeveloper** [Global-Flood-Assessment/MoMProduction#75]

**Comment by webgisdeveloper** [comment]
The main issue is the token, get a new token https://nrt4.modaps.eosdis.nasa.gov/

**Comment by webgisdeveloper** [comment]
error on the missing layer
```
Input file size is 4800, 4800

0...10...20...30...40...50...60...70...80...90...100 - done.

0...10...20...30...40...50...60...70...80...90...100 - done.

Traceback (most recent call last):

  File "rasterio/_base.pyx", line 261, in rasterio._base.DatasetBase.__init__

  File "rasterio/_shim.pyx", line 78, in rasterio._shim.open_dataset

  File "rasterio/_err.pyx", line 215, in rasterio._err.exc_wrap_pointer

rasterio._err.CPLE_OpenFailedError: Flood_2-Day_250m.vrt: No such file or directory

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "/home/nasa/MoMProduction/DFO_tool.py", line 334, in <module>

    main()

  File "/home/nasa/MoMProduction/DFO_tool.py", line 331, in main

    DFO_cron()

  File "/home/nasa/MoMProduction/DFO_tool.py", line 323, in DFO_cron

    DFO_process(key,datelist[key])

  File "/home/nasa/MoMProduction/DFO_tool.py", line 252, in DFO_process

    dfo_extract_by_watershed(vrt)

  File "/home/nasa/MoMProduction/DFO_tool.py", line 164, in dfo_extract_by_watershed

    dfoarea = dfo_extract_by_mask(vtk_file, test_json)

  File "/home/nasa/MoMProduction/DFO_tool.py", line 110, in dfo_extract_by_mask

    with rasterio.open(vrt_file) as src:

  File "/opt/miniconda3/envs/mom/lib/python3.9/site-packages/rasterio/env.py", line 435, in wrapper

    return f(*args, **kwds)

  File "/opt/miniconda3/envs/mom/lib/python3.9/site-packages/rasterio/__init__.py", line 220, in open

    s = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)

  File "rasterio/_base.pyx", line 263, in rasterio._base.DatasetBase.__init__

rasterio.errors.RasterioIOError: Flood_2-Day_250m.vrt: No such file or directory
```
